apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-runner
  namespace: sallyom-vteam
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claude-runner
rules:
- apiGroups: ["vteam.ambient-code"]
  resources: ["agenticsessions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["vteam.ambient-code"]
  resources: ["agenticsessions/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: claude-runner-sallyom-vteam
subjects:
- kind: ServiceAccount
  name: claude-runner
  namespace: sallyom-vteam
roleRef:
  kind: ClusterRole
  name: claude-runner
  apiGroup: rbac.authorization.k8s.io