apiVersion: v1
kind: Namespace
metadata:
  name: ambient-code
  labels:
    name: ambient-code
    app: vteam
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "vTeam Ambient Agentic Runner - AI-powered automation system"
    openshift.io/display-name: "vTeam Ambient Runner"
