apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhoai-uploads-pvc
  labels:
    app: rhoai-ai-feature-sizing
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhoai-output-pvc
  labels:
    app: rhoai-ai-feature-sizing
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
