services:
  # Jira MCP Server
  jira-mcp:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    ports:
      - "9000:9000"
    environment:
      - JIRA_URL=${JIRA_URL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - PORT=9000
    command: ["--transport", "sse", "-vv"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/healthz"]
      interval: 45s
      timeout: 10s
      retries: 3

  # Llama Stack Server with Ollama distribution
  llama-stack:
    image: llamastack/distribution-ollama:latest
    ports:
      - "8321:8321"
    volumes:
      - ~/.llama:/root/.llama
    environment:
      - INFERENCE_MODEL=${INFERENCE_MODEL}
      - OLLAMA_URL=${OLLAMA_URL}
    command:
      [
        "--port",
        "8321",
        "--env",
        "INFERENCE_MODEL=${INFERENCE_MODEL}",
        "--env",
        "OLLAMA_URL=${OLLAMA_URL}",
      ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8321/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
