apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projectsettings.vteam.ambient-code
spec:
  group: vteam.ambient-code
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-validations:
        - rule: "self.metadata.name == 'projectsettings'"
          message: "metadata.name must be 'projectsettings' (singleton per namespace)"
        properties:
          spec:
            type: object
            required:
            - groupAccess
            properties:
              groupAccess:
                type: array
                description: "Group access configuration creating RoleBindings"
                items:
                  type: object
                  required:
                  - groupName
                  - role
                  properties:
                    groupName:
                      type: string
                      description: "Name of the group to grant access"
                    role:
                      type: string
                      enum:
                      - "admin"
                      - "edit"
                      - "view"
                      description: "Role to assign to the group (admin/edit/view)"
              runnerSecretsName:
                type: string
                description: "Name of the Kubernetes Secret in this namespace that stores runner configuration key/value pairs"
          status:
            type: object
            properties:
              groupBindingsCreated:
                type: integer
                minimum: 0
                description: "Number of group RoleBindings successfully created"
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: projectsettings
    singular: projectsetting
    kind: ProjectSettings
    shortNames:
    - ps


