apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rfeworkflows.vteam.ambient-code
spec:
  group: vteam.ambient-code
  names:
    kind: RFEWorkflow
    listKind: RFEWorkflowList
    plural: rfeworkflows
    singular: rfeworkflow
    shortNames:
    - rfe
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required: [title, description, targetRepoUrl, targetRepoBranch]
            properties:
              project:
                type: string
              title:
                type: string
              description:
                type: string
              selectedAgents:
                type: array
                items:
                  type: string
              targetRepoUrl:
                type: string
              targetRepoBranch:
                type: string
          status:
            type: object
            properties:
              status:
                type: string
              currentPhase:
                type: string
              agentSessions:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    agentPersona:
                      type: string
                    phase:
                      type: string
                    state:
                      type: string
                    startedAt:
                      type: string
                    completedAt:
                      type: string
              artifacts:
                type: array
                items:
                  type: object
                  properties:
                    path:
                      type: string
                    name:
                      type: string
                    type:
                      type: string
                    phase:
                      type: string
                    createdBy:
                      type: string
                    size:
                      type: integer
                    modifiedAt:
                      type: string
              phaseResults:
                type: object
    subresources:
      status: {}

